@namespace
class SpriteKind:
    coin = SpriteKind.create()

def on_overlap_tile(sprite, location):
    info.change_score_by(1)
    music.ba_ding.play()
    game.splash("whatever ig eso")
    tiles.set_tile_at(tiles.get_tile_location(0, 0),
        assets.tile("""
            myTile0
        """))
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile0
    """),
    on_overlap_tile)

def on_overlap_tile2(sprite, location):
    game.over(True)
    effects.confetti.start_screen_effect()
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.button_pink_depressed,
    on_overlap_tile2)

def on_a_pressed():
    global projectile
    projectile = sprites.create_projectile_from_sprite(img("""
            . . . . . . f . . . . . . . . . 
                    . . . . . . . f . . . . . . . . 
                    . . . . . f . . f . . . . . . . 
                    . . . . . . f . . f . . . . . . 
                    . . . f . . . f . . f . . . . . 
                    . . . . f . . . f . f . . . . . 
                    . . . . . f . . f . f . . . . . 
                    . . . . . f . . f . f . . . . . 
                    . . . . f . . . f . f . . . . . 
                    . . . f . . . f . . f . . . . . 
                    . . . . . . f . . f . . . . . . 
                    . . . . . f . . f . . . . . . . 
                    . . . . . . . f . . . . . . . . 
                    . . . . . . f . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        mySprite,
        50,
        0)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_life_zero():
    game.over(False, effects.blizzard)
info.on_life_zero(on_life_zero)

projectile: Sprite = None
mySprite: Sprite = None
mySprite = sprites.create(img("""
        ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.player)
scp2 = sprites.create(assets.image("""
    myImage
"""), SpriteKind.enemy)
SCP3 = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f . . . . . . . 
            . . . . . f f 1 f f . . . . . . 
            . . . . . f f f f f . . . . . . 
            . . . . . f f 1 f f . . . . f . 
            . . . . f f f f f f f . . . f . 
            . . . f . f f 1 f f . f . f . . 
            . . f . . f f f f f . . f . . . 
            . . . f . . f . f . . . . . . . 
            . . . . . f . . . f . . . . . . 
            . . . . f . . . . . f . . . . . 
            . . . . . f . . . f . . . . . . 
            . . . . f f . . . f f . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.enemy)
SCP4 = sprites.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . f f f f . f f f f . . . 
            . . . . f f 1 f f f f f f . . . 
            . . . f f f f f 1 f f f f . . . 
            . . . . f f f f f f f 1 f . f f 
            . . . . f f f 1 f f 1 f f f f . 
            f f f f f f f f 1 f f f f f . . 
            f . . . f f 1 f f f f 1 f . f . 
            . f . . f f f 1 f f f f f . . . 
            . . . . f f f f f f f f f . . . 
            . . . . f f f f f 1 f f f . . . 
            . . . . . f f f f f f f . . . . 
            . . . . . . f . . . . f . . . . 
            . . . . . . f f . . f f . . . .
    """),
    SpriteKind.enemy)
controller.move_sprite(mySprite, 100, 100)
scp2.set_position(67, 89)
SCP4.set_position(158, 116)
scp2.follow(mySprite, 10)
SCP3.set_position(139, 93)
SCP3.follow(mySprite, 5)
SCP4.follow(mySprite, 5)
scene.set_background_color(0)
tiles.set_tilemap(tilemap("""
    level1
"""))
tiles.place_on_random_tile(mySprite, sprites.dungeon.stair_large)
scene.camera_follow_sprite(mySprite)
info.set_score(0)
info.set_life(3)
animation.run_image_animation(mySprite,
    [img("""
            ........................
                ........................
                ........................
                ........................
                ..........fffff.........
                ........ff11111f........
                .......fb111111bf.......
                ......fbd1111111f.......
                ......fddd111111df......
                ......fdddd11111df......
                ......fddddddd11df......
                ......fddddddd111f......
                ......fddddddcf11f......
                .......fbdddb1111bf.....
                ........fffcfdb1b1f.....
                .......ffffffffbfbf.....
                ....ff.fffffffffff......
                .....ffffffff...........
                .....ffffffb1b1f........
                ......ffffffbfbf........
                ........................
                ........................
                ........................
                ........................
        """),
        img("""
            ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......fd1111111f.......
                ......fdd1111111df......
                ......fddd111111df......
                ......fdddddd111df......
                ......fbddddbfd1df......
                ......fcbbbdcfddbf......
                .......fcbb11111f.......
                ........fffff1b1f.......
                ........fb111cfbf.......
                ........ffb1b1ff........
                ......f.fffbfbf.........
                ......ffffffff..........
                .......fffff............
                ........................
                ........................
                ........................
                ........................
        """)],
    500,
    True)

def on_forever():
    if mySprite.overlaps_with(scp2):
        mySprite.say("Oh no!", 2000)
        scp2.destroy(effects.ashes, 1000)
        music.wawawawaa.play()
        info.change_life_by(-1)
forever(on_forever)

def on_forever2():
    if mySprite.overlaps_with(SCP4):
        mySprite.say("Oh no!", 2000)
        SCP4.destroy(effects.ashes, 1000)
        music.wawawawaa.play()
        info.change_life_by(-1)
forever(on_forever2)

def on_forever3():
    if mySprite.overlaps_with(SCP3):
        mySprite.say("Oh no!", 2000)
        SCP3.destroy(effects.ashes, 1000)
        music.wawawawaa.play()
        info.change_life_by(-1)
forever(on_forever3)
